version: 0.2
env:
  variables:
    PRX_SPIRE_ECR_PKG_PARAMETERS: ELIXIR_APP=/prx/stag/Spire/Dovetail-Castle/pkg/docker-image-tag
    PRX_BUILD_AARCH64: "true"
  parameter-store:
    DOCKERHUB_USERNAME: /prx/DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: /prx/DOCKERHUB_PASSWORD
  exported-variables:
    - PRX_SPIRE_ECR_PKG_PARAMETERS
    - ELIXIR_APP
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - cp env-example .env
      - docker-compose build
      - docker-compose run castle test
  post_build:
    commands:
      - curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/main/ci/utility/post_build.sh"
      - chmod +x post_build.sh
      - . ./post_build.sh
