version: "2"
services:
  castle:
    build: .
    image: castle_app
    volumes:
      - ./_build_docker_compose:/app/_build
      - ./deps_docker_compose:/app/deps
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./test:/app/test
      - ./web:/app/web
    env_file:
      - .env
    links:
      - redis
    ports:
      - "4000:4000"
    command: phoenix.server
    environment:
      VIRTUAL_HOST: castle.prx.docker
      REDIS_HOST: redis
      MIX_ENV:
  redis:
    image: redis
    ports:
      - "6379:6379"
