castle:
  build: .
  volumes:
    - ./_build_docker_compose:/opt/app/_build
    - ./deps_docker_compose:/opt/app/deps
    - ./config:/opt/app/config
    - ./lib:/opt/app/lib
    - ./priv:/opt/app/priv
    - ./test:/opt/app/test
    - ./bin:/opt/app/bin
  env_file:
    - .env
  links:
    - redis
  ports:
    - "4000:4000"
  command: web
  environment:
    VIRTUAL_HOST: castle.prx.docker
    REDIS_HOST: redis
    REDIS_PORT: 6379
    MIX_ENV:
redis:
  image: redis
  ports:
    - "6379:6379"
