castle:
  build: .
  env_file:
    - env-example
  links:
    - redis
    - db
  command: test
  environment:
    VIRTUAL_HOST: castle.prx.docker
    REDIS_HOST: redis
    REDIS_PORT: 6379
    PG_DATABASE: castle_test
    PG_HOST: db
    PG_USER: castle_user
    PG_PASSWORD: password
    MIX_ENV: test
redis:
  image: redis
  ports:
    - "6379:6379"
db:
  image: postgres
  environment:
    POSTGRES_DB: castle_test
    POSTGRES_USER: castle_user
    POSTGRES_PASSWORD: password
  expose:
    - "5432"
