version: '3.4'
services:
  castle:
    build:
      context: .
      target: builder
    command: web
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: castle.prx.docker
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_DATABASE: castle_development
      PG_HOST: db
      PG_USER: castle_user
      PG_PASSWORD: password
    links:
      - redis
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./mix.exs:/opt/app/mix.exs
      - ./mix.lock:/opt/app/mix.lock
      - ./bin:/opt/app/bin
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./test:/opt/app/test
      # persistent dependencies
      - build-cache:/opt/app/_build
      - deps-cache:/opt/app/deps
  redis:
    image: redis
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: castle_development
      POSTGRES_USER: castle_user
      POSTGRES_PASSWORD: password
  castle-built:
    build:
      context: .
      target: built
    command: okay
volumes:
  build-cache:
  deps-cache:
